In [1]:
import os
from pathlib import Path
from ultralytics import YOLO
from PIL import Image
import shutil
import pandas as pd
from source import image_id_converter as img_idc
from source.db_loader import MLDataLoader
from source.db_loader import delete_images
#from source import sort_img_files as sif
from source import llm_input as llm_i
from source import llm_output as llm_o
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
import seaborn as sns
import numpy as np

In [2]:
import ollama
import json
import re
import pickle

In [3]:
import pandas as pd
import psycopg2
from dotenv import load_dotenv

In [4]:
import glob

In [5]:
from psycopg2.extras import execute_batch
from typing import Dict, List, Optional

In [6]:
# Standard library imports
import sys
from datetime import datetime
from pathlib import Path

# Database connection library
# psycopg2: PostgreSQL adapter for Python - handles all DB communication
import psycopg2
from psycopg2 import extras  # extras provides advanced features like Json adapter

# Data manipulation
import pandas as pd  # For handling CSV files and DataFrames

# Environment variable management
# python-dotenv: Loads database credentials from .env file (keeps passwords out of code)
from dotenv import load_dotenv

In [44]:
def get_existing_image_ids(source_filter, db_env, conn=None, cur=None):
    """
    Get all source_image_ids from database.
    
    Parameters:
    -----------
    source_filter : str
        Source to filter by (e.g., 'giub')
    conn : connection object, optional
        Existing database connection (if None, creates new one)
    cur : cursor object, optional
        Existing cursor (if None, creates new one)
    
    Returns:
    --------
    list : List of source_image_ids
    """
    import psycopg2
    from dotenv import load_dotenv
    import os
    
    close_after = False
    if conn is None:
        load_dotenv()
        conn = psycopg2.connect(
            dbname=os.getenv('DB_NAME'),
            user=os.getenv('DB_USER'),
            password=os.getenv('DB_PASSWORD'),
            host=os.getenv('DB_HOST'),
            port=os.getenv('DB_PORT')
        )
        cur = conn.cursor()
        close_after = True
    elif cur is None:
        cur = conn.cursor()
    
    # Added WHERE clause with parameter
    cur.execute("""
        SELECT DISTINCT source_image_id 
        FROM images 
        WHERE source = %s 
        ORDER BY source_image_id;
    """, (source_filter,))
                    
    existing_ids = [row[0] for row in cur.fetchall()]
    print(f"Existing image IDs for source '{source_filter}': {existing_ids}")
    
    if close_after:
        cur.close()
        conn.close()
    
    return existing_ids

### Set database_name:

In [8]:
#database_name = 'image_analysis_dev'
database_name = 'image_analysis_test'

db_env = '.env.test'

# Load test environment (override=True ensures it replaces any previously loaded values)
load_dotenv(db_env, override=True)

True

### Empty database:

# ============================================================================
# EMPTY DATABASE - Delete All Data
# ============================================================================
# Run this to reset database for testing data reload
# CASCADE handles all foreign key dependencies automatically

import psycopg2
from dotenv import load_dotenv
import os

load_dotenv()

# Connect to database
conn = psycopg2.connect(
    dbname=os.getenv('DB_NAME'),
    user=os.getenv('DB_USER'),
    password=os.getenv('DB_PASSWORD'),
    host=os.getenv('DB_HOST'),
    port=os.getenv('DB_PORT')
)
cur = conn.cursor()

print("🗑️  Deleting all data from database...")

# Delete data (CASCADE handles dependencies)
cur.execute("DELETE FROM images WHERE source = 'visual_genome';")
print(f"   Deleted {cur.rowcount} images (CASCADE deleted related data)")

cur.execute("DELETE FROM analysis_runs;")
print(f"   Deleted {cur.rowcount} analysis runs")

cur.execute("DELETE FROM prompts;")
print(f"   Deleted {cur.rowcount} prompts")

# Commit changes
conn.commit()

# Verify everything is deleted
cur.execute("""
    SELECT 
        (SELECT COUNT(*) FROM images) as images,
        (SELECT COUNT(*) FROM ground_truth_history) as ground_truth,
        (SELECT COUNT(*) FROM predictions) as predictions,
        (SELECT COUNT(*) FROM llm_responses) as llm_responses,
        (SELECT COUNT(*) FROM analysis_runs) as runs,
        (SELECT COUNT(*) FROM prompts) as prompts
""")

result = cur.fetchone()
print(f"\n✅ Database emptied. Current counts:")
print(f"   Images: {result[0]}")
print(f"   Ground truth: {result[1]}")
print(f"   Predictions: {result[2]}")
print(f"   LLM responses: {result[3]}")
print(f"   Analysis runs: {result[4]}")
print(f"   Prompts: {result[5]}")

# All should be 0
if all(count == 0 for count in result):
    print("\n🎉 Database is empty and ready for fresh data!")
else:
    print("\n⚠️  Warning: Some data remains")

# Close connection
cur.close()
conn.close()

#### If necessary use this:
loader.conn.rollback()

### Set paths:

In [9]:
project_path = Path.cwd()

visual_genome_path = (project_path/ '..' /'data_folders' / 'visual_genome_data').resolve()
visual_genome_proc_path = (project_path/ '..' /'data_folders' / 'visual_genome_proc_data').resolve()

### Check files:

In [10]:
vg_files = sorted([f for f in os.listdir(visual_genome_path) if not f.endswith('.jpg')], 
                  key=lambda f: os.path.getmtime(os.path.join(visual_genome_path, f)), 
                  reverse=True)
vg_files

['times_clustering_pipeline_20260208_225215.pkl',
 'results_clustering_pipeline_20260208_225215.pkl',
 'metadata_results_clustering.pkl',
 '.DS_Store',
 'labels.csv',
 'archive',
 'info_release_1.4.tex',
 'object_synsets.json',
 'objects_3.json',
 'objects.json',
 'objects_5.json']

### Set file paramters:

In [11]:
file_source = 'visual_genome' # Institute of Geography, University of Berne.
file_extension = '.jpg' # First batch of images obtained from the institute of Geography (giub)
filename_tag = 'visual_genome_proc' # First batch of images obtained from the institute of Geography (giub)
labels_file = 'labels.csv' # File containing ids and labels.
times_file = 'times_clustering_pipeline_20260208_225215.pkl' # File containing timestamp and duration of analysis-run.
metadata_results_file = 'results_clustering_pipeline_20260208_225215.pkl'
#responses_file = 'responses_llm_people_detect_multi_approach_20260213_144241.pkl'
#model_name_file = 'minicpm_v_model_info.txt'
#metadata_results_file = 'metadata_results_clustering.pkl'

### Set analysis rung parameters:

In [12]:
analysis_type = 'clustering with autoencoder'
model_name = 'cdae_model'
#model_version = model_version
python_script = 'img_to_pytorch.ipynb'

### Get file path of trained model:

In [13]:
models_file_path = project_path / model_name
models = os.listdir(models_file_path)
models.sort(reverse=True)
print(len(models))
models[0:3]

60

['model_059.pth', 'model_058.pth', 'model_057.pth']

In [14]:
fully_trained_model = models[0]
model_file_path = str(project_path / model_name / fully_trained_model)
model_file_path

'/Users/stephanehess/Documents/CAS_AML/dias_digit_project/project_clean/cdae_model/model_059.pth'

### Check environment variables:

In [15]:
import os
from pathlib import Path

# Check if .env exists in current directory
env_path = Path(db_env)
print(f"Current directory: {os.getcwd()}")
print(f".env exists: {env_path.exists()}")

# If loaded, check what environment variables are available
print(f"\nDB_NAME: {os.getenv('DB_NAME')}")
print(f"DB_USER: {os.getenv('DB_USER')}")
print(f"DB_HOST: {os.getenv('DB_HOST')}")
print(f"DB_PORT: {os.getenv('DB_PORT')}")

Current directory: /Users/stephanehess/Documents/CAS_AML/dias_digit_project/project_clean
.env exists: True

DB_NAME: image_analysis_test
DB_USER: stephanehess
DB_HOST: localhost
DB_PORT: 5432

### Load images:

### Get filepaths of images in folder:

In [16]:
file_path = visual_genome_proc_path / labels_file

# Load CSV
label_data = pd.read_csv(file_path)

# Get image paths from labels file and convert image paths to Path objects
vg_files = [Path(p) for p in label_data['file_paths']]

print('Number of vg files:')
print(len(vg_files))
print('Compare file id with filepath:')
print(label_data.file_paths[400])
print(label_data.image_id[400])
print(label_data.head())

Number of vg files:
5354
Compare file id with filepath:
/Users/stephanehess/Documents/CAS_AML/dias_digit_project/data_folders/visual_genome_proc_data/visual_genome_proc_1490.jpg
1490
   image_id                                         file_paths  buildings
0         1  /Users/stephanehess/Documents/CAS_AML/dias_dig...          1
1         2  /Users/stephanehess/Documents/CAS_AML/dias_dig...          1
2         9  /Users/stephanehess/Documents/CAS_AML/dias_dig...          1
3        11  /Users/stephanehess/Documents/CAS_AML/dias_dig...          1
4        16  /Users/stephanehess/Documents/CAS_AML/dias_dig...          1

In [17]:
label_data.head()

   image_id                                         file_paths  buildings
0         1  /Users/stephanehess/Documents/CAS_AML/dias_dig...          1
1         2  /Users/stephanehess/Documents/CAS_AML/dias_dig...          1
2         9  /Users/stephanehess/Documents/CAS_AML/dias_dig...          1
3        11  /Users/stephanehess/Documents/CAS_AML/dias_dig...          1
4        16  /Users/stephanehess/Documents/CAS_AML/dias_dig...          1

In [18]:
label_data.shape

(5354, 3)

### Get ID's of images in the database (filtered by source):

In [19]:
# file_source: 'giub'
get_existing_image_ids(source_filter='giub', db_env=db_env, conn=None, cur=None)

Existing image IDs for source 'giub': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111]

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111]

In [45]:
# file_source: 'visual_genome'
get_existing_image_ids(source_filter=file_source, db_env=db_env, conn=None, cur=None)

Existing image IDs for source 'visual_genome': [1, 2, 9, 11, 16, 22, 23, 24, 25, 26, 29, 38, 42, 45, 47, 48, 49, 52, 53, 54, 55, 56, 57, 58, 59, 61, 87, 95, 99, 101, 102, 103, 104, 105, 108, 109, 113, 117, 120, 126, 130, 134, 135, 136, 137, 138, 141, 142, 144, 145, 150, 157, 158, 164, 165, 169, 172, 176, 179, 180, 181, 185, 188, 189, 190, 194, 197, 199, 201, 202, 203, 204, 205, 206, 208, 210, 212, 214, 215, 217, 218, 222, 224, 225, 226, 227, 228, 229, 231, 235, 236, 237, 243, 245, 246, 248, 250, 253, 255, 256, 257, 261, 262, 264, 266, 267, 269, 270, 271, 272, 273, 275, 276, 277, 279, 281, 282, 283, 285, 286, 287, 289, 290, 294, 297, 298, 301, 302, 303, 304, 305, 306, 308, 310, 311, 313, 314, 317, 319, 320, 321, 326, 327, 333, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 353, 354, 355, 361, 362, 364, 366, 368, 373, 374, 376, 397, 400, 401, 402, 407, 421, 422, 423, 425, 426, 427, 428, 430, 431, 432, 434, 435, 436, 437, 438, 439, 440, 443, 444, 445, 449, 451, 455, 456, 457, 458, 459, 460, 462, 463, 464, 465, 467, 469, 470, 471, 472, 477, 479, 480, 481, 485, 486, 487, 488, 491, 498, 513, 514, 515, 518, 521, 530, 536, 539, 547, 558, 561, 576, 577, 581, 582, 585, 588, 589, 590, 591, 592, 594, 596, 597, 599, 600, 601, 602, 604, 605, 606, 607, 608, 609, 610, 614, 617, 618, 619, 620, 621, 624, 626, 627, 629, 630, 632, 633, 635, 636, 638, 639, 644, 645, 647, 648, 649, 650, 651, 653, 654, 655, 657, 658, 660, 663, 666, 669, 670, 671, 672, 673, 674, 675, 677, 678, 681, 684, 687, 688, 689, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 711, 712, 713, 714, 715, 716, 719, 720, 721, 722, 723, 725, 726, 727, 728, 729, 731, 733, 734, 736, 737, 738, 740, 741, 742, 743, 744, 745, 746, 747, 749, 750, 752, 753, 754, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 769, 770, 771, 772, 773, 774, 776, 778, 779, 780, 782, 785, 786, 788, 789, 790, 791, 792, 795, 796, 800, 802, 804, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 817, 818, 819, 820, 821, 822, 823, 826, 829, 832, 833, 834, 837, 838, 839, 840, 843, 844, 845, 848, 849, 850, 857, 858, 859, 860, 861, 862, 864, 865, 867, 869, 871, 872, 873, 874, 875, 876, 878, 879, 880, 887, 889, 891, 892, 893, 894, 896, 901, 903, 904, 908, 911, 913, 915, 921, 922, 925, 928, 933, 937, 938, 939, 940, 941, 942, 943, 947, 949, 950, 951, 952, 953, 959, 961, 963, 965, 967, 969, 971, 972, 973, 975, 976, 977, 978, 980, 981, 982, 983, 985, 991, 992, 993, 999, 1002, 1012, 1028, 1031, 1049, 1105, 1116, 1123, 1241, 1268, 1292, 1321, 1357, 1367, 1413, 1415, 1426, 1428, 1430, 1436, 1449, 1455, 1456, 1477, 1490, 1505, 1531, 1559, 1570, 1574, 1577, 1579, 1582, 1588, 1595, 1623, 1631, 1632, 1649, 1652, 1653, 1654, 1655, 1656, 1659, 1707, 1769, 1810, 1818, 1838, 1842, 1856, 1892, 1896, 1918, 1930, 1936, 1939, 1947, 1948, 1949, 1965, 2084, 2107, 2121, 2135, 2176, 2226, 2229, 2267, 2285, 2302, 2314, 2325, 2329, 2336, 2353, 2354, 2361, 2362, 2363, 2365, 2366, 2384, 2402, 2403, 2420, 2425, 2433, 2445, 2460, 2461, 2462, 2464, 2467, 2472, 2492, 2495, 2504, 2506, 2522, 2524, 2528, 2541, 2546, 2548, 2552, 2553, 2554, 2557, 2559, 2562, 2569, 2579, 2648, 2685, 2703, 2713, 2719, 2729, 2733, 2740, 2751, 2769, 2779, 2790, 2807, 2819, 2828, 2830, 2837, 2839, 2844, 2846, 2847, 2850, 2852, 2853, 2855, 2860, 2861, 2862, 2863, 2865, 2866, 2876, 2881, 2885, 2893, 2894, 2897, 2912, 2917, 2924, 2931, 2934, 2935, 2940, 2949, 2978, 2982, 2983, 2990, 2998, 3000, 3004, 3036, 3037, 3050, 3056, 3060, 3066, 3119, 3127, 3135, 3149, 3176, 3178, 3206, 3243, 3249, 3253, 3255, 3261, 3265, 3274, 3275, 3278, 3289, 3301, 3306, 3311, 3321, 3325, 3327, 3341, 3342, 3344, 3359, 3377, 3383, 3401, 3419, 3428, 3429, 3436, 3438, 3439, 3441, 3442, 3443, 3445, 3450, 3478, 3483, 3490, 3508, 3524, 3533, 3536, 3544, 3545, 3547, 3570, 3596, 3627, 3638, 3640, 3664, 3666, 3669, 3676, 3689, 3717, 3723, 3724, 3729, 3731, 3733, 3749, 3762, 3763, 3771, 3772, 3782, 3790, 3794, 3795, 3805, 3818, 3822, 3827, 3829, 3842, 3878, 3895, 3920, 3938, 3959, 3995, 4010, 4012, 4039, 4118, 4120, 4121, 4128, 4134, 4148, 4149, 4151, 4155, 4164, 4166, 4181, 4200, 4203, 4208, 4209, 4210, 4231, 4235, 4242, 4245, 4252, 4256, 4263, 4303, 4316, 4317, 4333, 4343, 4348, 4354, 4355, 4361, 4368, 4376, 4384, 4386, 4389, 4396, 4412, 4415, 4460, 4462, 4465, 4476, 4502, 4518, 4528, 4532, 4533, 4534, 4538, 4561, 4569, 4576, 4598, 4624, 4646, 4668, 4670, 4672, 4678, 4681, 4683, 4832, 4845, 4956, 4968, 4982, 4998, 61511, 61512, 61513, 61514, 61515, 61517, 61518, 61519, 61520, 61521, 61523, 61526, 61528, 61531, 61532, 61534, 61535, 61538, 61540, 61542, 61544, 61546, 61548, 61549, 61552, 61554, 61558, 61564, 61566, 61568, 61569, 61574, 61576, 61577, 61578, 61579, 61580, 61581, 61584, 61587, 61588, 61589, 61591, 61595, 61600, 61604, 61606, 61609, 61610, 107899, 107902, 107904, 107906, 107910, 107911, 107914, 107917, 107918, 107919, 107920, 107921, 107923, 107924, 107926, 107927, 107928, 107929, 107931, 107936, 107937, 107938, 107943, 107945, 107947, 107949, 107951, 107953, 107959, 107971, 107972, 107973, 107974, 107980, 107981, 107983, 107984, 107986, 107990, 107991, 107992, 107994, 107995, 107997, 150260, 150261, 150263, 150264, 150265, 150267, 150269, 150270, 150276, 150277, 150279, 150280, 150289, 150291, 150294, 150295, 150297, 150301, 150302, 150303, 150306, 150307, 150308, 150309, 150311, 150312, 150314, 150315, 150316, 150317, 150318, 150322, 150324, 150325, 150326, 150327, 150330, 150331, 150332, 150335, 150338, 150341, 150342, 150343, 150345, 150348, 150349, 150351, 150352, 150353, 150356, 150357, 150358, 150359, 150360, 150361, 150364, 150368, 150371, 150372, 150378, 150380, 150382, 150383, 150384, 150385, 150387, 150389, 150390, 150392, 150393, 150395, 150400, 150408, 150409, 150410, 150413, 150414, 150416, 150420, 150423, 150425, 150430, 150431, 150432, 150433, 150434, 150435, 150436, 150439, 150442, 150444, 150445, 150447, 150450, 150451, 150452, 150453, 150455, 150456, 150458, 150463, 150464, 150466, 150467, 150468, 150469, 150470, 150471, 150472, 150476, 150478, 150481, 150482, 150484, 150486, 150488, 150490, 150491, 150499, 150500, 150511, 150513, 150514, 150515, 150518, 150520, 150522, 150525, 150527, 150531, 150532, 150533, 150535, 150537, 150538, 150540, 150541, 150544, 150547, 150549, 150550, 150551, 150555, 285605, 285607, 285608, 285609, 285610, 285614, 285616, 285620, 285621, 285626, 285629, 285635, 285636, 285639, 285640, 285641, 285642, 285645, 285646, 285648, 285649, 285650, 285651, 285658, 285660, 285662, 285663, 285664, 285665, 285668, 285670, 285673, 285674, 285675, 285677, 285681, 285687, 285692, 285693, 285699, 285701, 285703, 285704, 285716, 285717, 285721, 285723, 285727, 285730, 285731, 285739, 285740, 285743, 285744, 285747, 285751, 285752, 285753, 285754, 285756, 285759, 285760, 285762, 285763, 285765, 285769, 285772, 285778, 285779, 285786, 285790, 285791, 285792, 285795, 285798, 285804, 285808, 285811, 285813, 285816, 285818, 285819, 285825, 285826, 285827, 285830, 285831, 285835, 285837, 285845, 285848, 285849, 285851, 285853, 285854, 285855, 285858, 285861, 285866, 285870, 285873, 285874, 285875, 285876, 285879, 285881, 285883, 285887, 285888, 285890, 285891, 285893, 285895, 285898, 285901, 285905, 285907, 285909, 285910, 285914, 285918, 285920, 285923, 285925, 285926, 285927, 285936, 285937, 285939, 285940, 285941, 285943, 285944, 285945, 285949, 285951, 285952, 285954, 285958, 285961, 285963, 285964, 285967, 285968, 285970, 285971, 285973, 285974, 285975, 285979, 285983, 285985, 285987, 285989, 285993, 285996, 285999, 286000, 286004, 286005, 286006, 286007, 286009, 286010, 286011, 286013, 286014, 286016, 286017, 286019, 286025, 286030, 286031, 286033, 286034, 286037, 286039, 286040, 286042, 286047, 286050, 286051, 286052, 286053, 286054, 286056, 286057, 286060, 286065, 286068, 286069, 286071, 286077, 286079, 286080, 286089, 286090, 286091, 286092, 286093, 286095, 286096, 286098, 497912, 497917, 497919, 497920, 497921, 497923, 497924, 497925, 497930, 497932, 497933, 497935, 497937, 497938, 497939, 497940, 497942, 497943, 497945, 497946, 497947, 497948, 497949, 497950, 497951, 497952, 497953, 497956, 497961, 497963, 497964, 497966, 497972, 497975, 497979, 497980, 497981, 497982, 497984, 497986, 497987, 497989, 497990, 497996, 497998, 497999, 498000, 498002, 498003, 498010, 498011, 498015, 498016, 498017, 498020, 498022, 498027, 498028, 498032, 498033, 498035, 498036, 498037, 498040, 498041, 498045, 498048, 498052, 498053, 498055, 498056, 498059, 498061, 498063, 498067, 498069, 498071, 498075, 498078, 498079, 498081, 498082, 498083, 498085, 498086, 498087, 498090, 498093, 498097, 498098, 498100, 498101, 498103, 498104, 498106, 498108, 498109, 498110, 498114, 498119, 498125, 498127, 498128, 498129, 498130, 498132, 498137, 498140, 498146, 498154, 498156, 498159, 498165, 498166, 498167, 498169, 498171, 498172, 498174, 498176, 498177, 498178, 498179, 498180, 498187, 498193, 498195, 498196, 498199, 498201, 498202, 498205, 498207, 498209, 498213, 498217, 498219, 498221, 498224, 498226, 498227, 498228, 498229, 498230, 498233, 498234, 498236, 498237, 498238, 498239, 498244, 498248, 498251, 498252, 498254, 498255, 498257, 498258, 498259, 498261, 498264, 498265, 498266, 498267, 498270, 498273, 498274, 498278, 498280, 498283, 498284, 498285, 498286, 498287, 498289, 498290, 498291, 498292, 498293, 498294, 498295, 498298, 498299, 498302, 498305, 498308, 498311, 498316, 498317, 498321, 498323, 498331, 498342, 498346, 498347, 498352, 498356, 498357, 498359, 498360, 498365, 498367, 498370, 498373, 498375, 498376, 498378, 498379, 498382, 498383, 498384, 498387, 498388, 498391, 498392, 498394, 498395, 498400, 498401, 498403, 498406, 498407, 498409, 498411, 712948, 712949, 712954, 712958, 712959, 712961, 712963, 712964, 712965, 712969, 712971, 712985, 712986, 712987, 712990, 712992, 712995, 712996, 712999, 713000, 713003, 713005, 713008, 713009, 713010, 713014, 713022, 713024, 713025, 713027, 713030, 713031, 713032, 713033, 713036, 713043, 713047, 713051, 713054, 713055, 713057, 713061, 713065, 713066, 713067, 713071, 713072, 713073, 713077, 713081, 713083, 713085, 713086, 713088, 713091, 713092, 713093, 713095, 713097, 713098, 713099, 713100, 713101, 713102, 713105, 713108, 713111, 713112, 713114, 713115, 713116, 713117, 713118, 713119, 713123, 713124, 713125, 713128, 713132, 713135, 713136, 713146, 713148, 713149, 713151, 713152, 713154, 713155, 713156, 713157, 713161, 713162, 713165, 713166, 713167, 713168, 713170, 713172, 713176, 713178, 713179, 713180, 713181, 713182, 713183, 713185, 713186, 713187, 713188, 713189, 713190, 713194, 713196, 713201, 713202, 713205, 713214, 713215, 713217, 713219, 713222, 713226, 713227, 713232, 713236, 713237, 713240, 713241, 713243, 713244, 713245, 713246, 713248, 713251, 713253, 713254, 713255, 713259, 713262, 713266, 713272, 713276, 713278, 713284, 713289, 713290, 713291, 713292, 713293, 713300, 713301, 713303, 713305, 713310, 713311, 713312, 713314, 713315, 713316, 713318, 713320, 713323, 713324, 713328, 713331, 713340, 713341, 713344, 713346, 713348, 713349, 713354, 713355, 713356, 713357, 713358, 713359, 713361, 713366, 713367, 713368, 713370, 713371, 713375, 713376, 713381, 713383, 713384, 713388, 713390, 713392, 713394, 713395, 713396, 713405, 713407, 713411, 713412, 713413, 713416, 713418, 713419, 713420, 713423, 713424, 713426, 713439, 713443, 713447, 713449, 713450, 713454, 713456, 713458, 713459, 713461, 713464, 713466, 713470, 713472, 713474, 713477, 713479, 713486, 713490, 713514, 713526, 713533, 713543, 713558, 713603, 713615, 713641, 713649, 713666, 713678, 713680, 713738, 713739, 713746, 713752, 713753, 713755, 713756, 713757, 713762, 713787, 713801, 713832, 713837, 713844, 713845, 713847, 713914, 713915, 713940, 713947, 1159271, 1159287, 1159327, 1159364, 1159372, 1159397, 1159407, 1159450, 1159459, 1159588, 1159615, 1159621, 1159635, 1159637, 1159649, 1159651, 1159653, 1159669, 1159674, 1159714, 1159769, 1159780, 1159848, 1159865, 1159872, 1159886, 1159900, 1159902, 1159915, 1159937, 1159972, 1159987, 1159996, 1160021, 1160095, 1160116, 1160123, 1160171, 1160207, 1591830, 1591852, 1591893, 1591899, 1591934, 1591951, 1591985, 1592003, 1592004, 1592056, 1592064, 1592066, 1592092, 1592132, 1592140, 1592141, 1592166, 1592169, 1592182, 1592187, 1592209, 1592220, 1592241, 1592249, 1592267, 1592352, 1592366, 1592388, 1592399, 1592415, 1592422, 1592468, 1592484, 1592499, 1592502, 1592505, 1592509, 1592511, 1592525, 1592545, 1592549, 1592558, 1592625, 1592627, 1592640, 1592653, 1592654, 1592655, 1592661, 1592663, 1592678, 1592684, 1592696, 1592711, 1592741, 1592768, 1592780, 1592794, 1592827, 1592830, 1592831, 1592857, 1592861, 1592896, 1592903, 1592921, 1592944, 1592955, 1592963, 1592999, 1593006, 1593009, 1593047, 1593050, 1593063, 1593076, 1593084, 1593109, 1593111, 1593114, 1593120, 1593135, 1593173, 1593199, 1593216, 1593217, 1593228, 1593230, 1593260, 2315427, 2315527, 2315686, 2315846, 2316002, 2316235, 2316377, 2316620, 2316709, 2316803, 2316901, 2316994, 2317021, 2317035, 2317112, 2317116, 2317126, 2317149, 2317226, 2317334, 2317389, 2317528, 2317545, 2317549, 2317760, 2317827, 2317975, 2318022, 2318127, 2318136, 2318144, 2318209, 2318241, 2318280, 2318354, 2318402, 2318542, 2318551, 2318552, 2318657, 2318659, 2318796, 2318964, 2318974, 2319072, 2319084, 2319197, 2319225, 2319266, 2319290, 2319351, 2319391, 2319432, 2319438, 2319489, 2319514, 2319662, 2319793, 2319882, 2320093, 2320221, 2320489, 2320632, 2320711, 2320778, 2320781, 2320863, 2320914, 2320933, 2321088, 2321125, 2321173, 2321301, 2321378, 2321426, 2321428, 2321444, 2321480, 2321779, 2321784, 2321885, 2322023, 2322025, 2322355, 2322428, 2322632, 2322689, 2322791, 2322927, 2322961, 2322970, 2323049, 2323090, 2323128, 2323439, 2323475, 2323479, 2323790, 2323874, 2323934, 2324092, 2324093, 2324102, 2324196, 2324281, 2324358, 2324365, 2324401, 2324422, 2324505, 2324533, 2324659, 2324676, 2324702, 2324725, 2324751, 2324754, 2324906, 2324941, 2324963, 2325213, 2325263, 2325458, 2325642, 2325743, 2325814, 2325816, 2325828, 2326101, 2326165, 2326203, 2326380, 2326396, 2326421, 2326472, 2326478, 2326699, 2326774, 2326826, 2326831, 2326905, 2327026, 2327217, 2327284, 2327391, 2327891, 2327964, 2328069, 2328168, 2328276, 2328581, 2328945, 2328966, 2329094, 2329096, 2329285, 2329354, 2329407, 2329562, 2329815, 2329828, 2329869, 2329879, 2329985, 2330405, 2330451, 2330478, 2330582, 2330688, 2330706, 2330745, 2331375, 2331530, 2331614, 2331861, 2331993, 2332112, 2332124, 2332151, 2332343, 2332358, 2332453, 2332638, 2332642, 2332668, 2332711, 2332834, 2332862, 2333048, 2333050, 2333085, 2333088, 2333244, 2333380, 2333502, 2333532, 2333538, 2333554, 2333563, 2333579, 2333627, 2333671, 2333834, 2334172, 2334385, 2334429, 2334449, 2334467, 2334515, 2334657, 2334748, 2334919, 2334970, 2335044, 2335049, 2335154, 2335179, 2335182, 2335185, 2335230, 2335341, 2335426, 2335468, 2335588, 2335628, 2335658, 2335744, 2335772, 2335777, 2335785, 2335807, 2335870, 2336069, 2336096, 2336159, 2336218, 2336461, 2336487, 2336586, 2336678, 2336695, 2336813, 2336834, 2336898, 2336964, 2337057, 2337061, 2337115, 2337362, 2337679, 2337831, 2337887, 2337899, 2337998, 2338000, 2338029, 2338033, 2338409, 2338468, 2338509, 2338624, 2338668, 2338812, 2338872, 2338947, 2338985, 2339046, 2339120, 2339167, 2339214, 2339231, 2339331, 2339429, 2339444, 2339449, 2339535, 2339576, 2339704, 2339710, 2339800, 2339865, 2339976, 2339998, 2340026, 2340141, 2340180, 2340441, 2340569, 2340695, 2340723, 2340795, 2340956, 2340987, 2341009, 2341054, 2341094, 2341190, 2341197, 2341269, 2341318, 2341324, 2341354, 2341450, 2341509, 2341539, 2341594, 2341636, 2341667, 2341766, 2341910, 2342013, 2342107, 2342162, 2342166, 2342259, 2342269, 2342291, 2342475, 2342621, 2342628, 2342734, 2343006, 2343182, 2343412, 2343533, 2343557, 2343578, 2343595, 2343740, 2343875, 2343934, 2344037, 2344176, 2344291, 2344330, 2344345, 2344364, 2344472, 2344477, 2344479, 2344620, 2344627, 2344629, 2344642, 2344720, 2344904, 2344994, 2345026, 2345106, 2345134, 2345336, 2345348, 2345374, 2345402, 2345434, 2345621, 2345622, 2345731, 2345785, 2345823, 2345886, 2345974, 2345985, 2346117, 2346244, 2346252, 2346302, 2346343, 2346370, 2346473, 2346489, 2346493, 2346603, 2346780, 2346788, 2346864, 2346876, 2346892, 2347077, 2347108, 2347117, 2347182, 2347187, 2347218, 2347304, 2347317, 2347325, 2347433, 2347588, 2347620, 2347666, 2347743, 2347763, 2347784, 2347812, 2347936, 2348027, 2348036, 2348055, 2348139, 2348163, 2348169, 2348228, 2348265, 2348275, 2348278, 2348289, 2348417, 2348510, 2348513, 2348582, 2348838, 2348968, 2348971, 2348973, 2349320, 2349352, 2349361, 2349390, 2349403, 2349440, 2349496, 2349504, 2349522, 2349570, 2349701, 2349755, 2349780, 2349800, 2349819, 2349931, 2350086, 2350093, 2350095, 2350108, 2350157, 2350158, 2350177, 2350217, 2350229, 2350231, 2350262, 2350276, 2350279, 2350282, 2350287, 2350304, 2350307, 2350316, 2350430, 2350444, 2350490, 2350492, 2350497, 2350512, 2350523, 2350551, 2350555, 2350619, 2350620, 2350628, 2350676, 2350681, 2350699, 2350718, 2350745, 2350775, 2350783, 2350851, 2350870, 2350884, 2350898, 2350907, 2350923, 2350940, 2350989, 2350992, 2351012, 2351155, 2351188, 2351191, 2351209, 2351225, 2351228, 2351232, 2351268, 2351282, 2351284, 2351288, 2351299, 2351307, 2351309, 2351324, 2351345, 2351405, 2351451, 2351472, 2351486, 2351495, 2351496, 2351500, 2351531, 2351536, 2351549, 2351608, 2351612, 2351636, 2351645, 2351650, 2351660, 2351662, 2351664, 2351667, 2351677, 2351694, 2351700, 2351702, 2351723, 2351747, 2351764, 2351775, 2351785, 2351823, 2351833, 2351857, 2351895, 2351900, 2352007, 2352008, 2352058, 2352090, 2352095, 2352103, 2352121, 2352139, 2352157, 2352175, 2352186, 2352204, 2352273, 2352277, 2352341, 2352344, 2352384, 2352393, 2352409, 2352446, 2352447, 2352451, 2352484, 2352486, 2352489, 2352538, 2352581, 2352602, 2352640, 2352661, 2352687, 2352754, 2352767, 2352785, 2352849, 2352856, 2352866, 2352892, 2352936, 2352937, 2352954, 2352989, 2352995, 2353021, 2353022, 2353039, 2353072, 2353124, 2353140, 2353166, 2353179, 2353398, 2353403, 2353409, 2353481, 2353496, 2353512, 2353537, 2353583, 2353589, 2353605, 2353619, 2353649, 2353653, 2353662, 2353701, 2353720, 2353726, 2353728, 2353731, 2353739, 2353740, 2353759, 2353772, 2353775, 2353776, 2353780, 2353804, 2353844, 2353881, 2353921, 2353930, 2353962, 2353966, 2353968, 2353972, 2353987, 2353996, 2354013, 2354022, 2354045, 2354047, 2354052, 2354075, 2354102, 2354119, 2354125, 2354126, 2354132, 2354139, 2354163, 2354171, 2354230, 2354237, 2354240, 2354247, 2354249, 2354270, 2354295, 2354329, 2354333, 2354336, 2354340, 2354364, 2354408, 2354431, 2354441, 2354455, 2354468, 2354470, 2354472, 2354524, 2354570, 2354572, 2354580, 2354595, 2354637, 2354660, 2354667, 2354719, 2354745, 2354759, 2354822, 2354831, 2354859, 2354897, 2354908, 2354921, 2354944, 2354986, 2355019, 2355027, 2355040, 2355046, 2355053, 2355063, 2355076, 2355102, 2355119, 2355125, 2355147, 2355149, 2355206, 2355215, 2355222, 2355248, 2355263, 2355323, 2355368, 2355384, 2355402, 2355430, 2355440, 2355445, 2355446, 2355472, 2355488, 2355496, 2355505, 2355508, 2355517, 2355576, 2355593, 2355640, 2355653, 2355654, 2355677, 2355718, 2355742, 2355768, 2355771, 2355786, 2355812, 2355838, 2355846, 2355862, 2355865, 2355866, 2355874, 2355922, 2355926, 2355937, 2355943, 2355960, 2355983, 2355989, 2356006, 2356019, 2356108, 2356124, 2356136, 2356183, 2356209, 2356224, 2356228, 2356273, 2356297, 2356334, 2356339, 2356359, 2356385, 2356389, 2356416, 2356444, 2356448, 2356451, 2356472, 2356496, 2356502, 2356503, 2356546, 2356547, 2356575, 2356612, 2356626, 2356641, 2356654, 2356671, 2356673, 2356696, 2356729, 2356742, 2356771, 2356773, 2356813, 2356816, 2356818, 2356825, 2356837, 2356854, 2356855, 2356866, 2356871, 2356884, 2356920, 2356949, 2356971, 2356973, 2357009, 2357021, 2357027, 2357031, 2357051, 2357086, 2357094, 2357102, 2357103, 2357105, 2357106, 2357109, 2357114, 2357146,

[1,
 2,
 9,
 11,
 16,
 22,
 23,
 24,
 25,
 26,
 29,
 38,
 42,
 45,
 47,
 48,
 49,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 61,
 87,
 95,
 99,
 101,
 102,
 103,
 104,
 105,
 108,
 109,
 113,
 117,
 120,
 126,
 130,
 134,
 135,
 136,
 137,
 138,
 141,
 142,
 144,
 145,
 150,
 157,
 158,
 164,
 165,
 169,
 172,
 176,
 179,
 180,
 181,
 185,
 188,
 189,
 190,
 194,
 197,
 199,
 201,
 202,
 203,
 204,
 205,
 206,
 208,
 210,
 212,
 214,
 215,
 217,
 218,
 222,
 224,
 225,
 226,
 227,
 228,
 229,
 231,
 235,
 236,
 237,
 243,
 245,
 246,
 248,
 250,
 253,
 255,
 256,
 257,
 261,
 262,
 264,
 266,
 267,
 269,
 270,
 271,
 272,
 273,
 275,
 276,
 277,
 279,
 281,
 282,
 283,
 285,
 286,
 287,
 289,
 290,
 294,
 297,
 298,
 301,
 302,
 303,
 304,
 305,
 306,
 308,
 310,
 311,
 313,
 314,
 317,
 319,
 320,
 321,
 326,
 327,
 333,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 353,
 354,
 355,
 361,
 362,
 364,
 366,
 368,
 373,
 374,
 376,
 397,
 400,
 401,
 402,
 407,
 421,
 422,
 423,
 425,
 426,
 427,
 428,
 430,
 431,
 432,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 443,
 444,
 445,
 449,
 451,
 455,
 456,
 457,
 458,
 459,
 460,
 462,
 463,
 464,
 465,
 467,
 469,
 470,
 471,
 472,
 477,
 479,
 480,
 481,
 485,
 486,
 487,
 488,
 491,
 498,
 513,
 514,
 515,
 518,
 521,
 530,
 536,
 539,
 547,
 558,
 561,
 576,
 577,
 581,
 582,
 585,
 588,
 589,
 590,
 591,
 592,
 594,
 596,
 597,
 599,
 600,
 601,
 602,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 614,
 617,
 618,
 619,
 620,
 621,
 624,
 626,
 627,
 629,
 630,
 632,
 633,
 635,
 636,
 638,
 639,
 644,
 645,
 647,
 648,
 649,
 650,
 651,
 653,
 654,
 655,
 657,
 658,
 660,
 663,
 666,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 677,
 678,
 681,
 684,
 687,
 688,
 689,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 711,
 712,
 713,
 714,
 715,
 716,
 719,
 720,
 721,
 722,
 723,
 725,
 726,
 727,
 728,
 729,
 731,
 733,
 734,
 736,
 737,
 738,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 749,
 750,
 752,
 753,
 754,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 769,
 770,
 771,
 772,
 773,
 774,
 776,
 778,
 779,
 780,
 782,
 785,
 786,
 788,
 789,
 790,
 791,
 792,
 795,
 796,
 800,
 802,
 804,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 826,
 829,
 832,
 833,
 834,
 837,
 838,
 839,
 840,
 843,
 844,
 845,
 848,
 849,
 850,
 857,
 858,
 859,
 860,
 861,
 862,
 864,
 865,
 867,
 869,
 871,
 872,
 873,
 874,
 875,
 876,
 878,
 879,
 880,
 887,
 889,
 891,
 892,
 893,
 894,
 896,
 901,
 903,
 904,
 908,
 911,
 913,
 915,
 921,
 922,
 925,
 928,
 933,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 947,
 949,
 950,
 951,
 952,
 953,
 959,
 961,
 963,
 965,
 967,
 969,
 971,
 972,
 973,
 975,
 976,
 977,
 978,
 980,
 981,
 982,
 983,
 985,
 991,
 992,
 993,
 999,
 1002,
 1012,
 1028,
 1031,
 1049,
 1105,
 1116,
 1123,
 1241,
 1268,
 1292,
 1321,
 1357,
 1367,
 1413,
 1415,
 1426,
 1428,
 1430,
 1436,
 1449,
 1455,
 1456,
 1477,
 1490,
 1505,
 1531,
 1559,
 1570,
 1574,
 1577,
 1579,
 1582,
 1588,
 1595,
 1623,
 1631,
 1632,
 1649,
 1652,
 1653,
 1654,
 1655,
 1656,
 1659,
 1707,
 1769,
 1810,
 1818,
 1838,
 1842,
 1856,
 1892,
 1896,
 1918,
 1930,
 1936,
 1939,
 1947,
 1948,
 1949,
 1965,
 2084,
 2107,
 2121,
 2135,
 2176,
 2226,
 2229,
 2267,
 2285,
 2302,
 2314,
 2325,
 2329,
 2336,
 2353,
 2354,
 2361,
 2362,
 2363,
 2365,
 2366,
 2384,
 2402,
 2403,
 2420,
 2425,
 2433,
 2445,
 2460,
 2461,
 2462,
 2464,
 2467,
 2472,
 2492,
 2495,
 2504,
 2506,
 2522,
 2524,
 2528,
 2541,
 2546,
 2548,
 2552,
 2553,
 2554,
 2557,
 2559,
 2562,
 2569,
 2579,
 2648,
 2685,
 2703,
 2713,
 2719,
 2729,
 2733,
 2740,
 2751,
 2769,
 2779,
 2790,
 2807,
 2819,
 2828,
 2830,
 2837,
 2839,
 2844,
 2846,
 2847,
 2850,
 2852,
 2853,
 2855,
 2860,
 2861,
 2862,
 2863,
 2865,
 2866,
 2876,
 2881,
 2885,
 2893,
 2894,
 2897,
 2912,
 2917,
 2924,
 2931,
 2934,
 2935,
 2940,
 2949,
 2978,
 2982,
 2983,
 2990,
 2998,
 3000,
 3004,
 3036,
 3037,
 3050,
 3056,
 3060,
 3066,
 3119,
 3127,
 3135,
 3149,
 3176,
 3178,
 3206,
 3243,
 3249,
 3253,
 3255,
 3261,
 3265,
 3274,
 3275,
 3278,
 3289,
 3301,
 3306,
 3311,
 3321,
 3325,
 3327,
 3341,
 3342,
 3344,
 3359,
 3377,
 3383,
 3401,
 3419,
 3428,
 3429,
 3436,
 3438,
 3439,
 3441,
 3442,
 3443,
 3445,
 3450,
 3478,
 3483,
 3490,
 3508,
 3524,
 3533,
 3536,
 3544,
 3545,
 3547,
 3570,
 3596,
 3627,
 3638,
 3640,
 3664,
 3666,
 3669,
 3676,
 3689,
 3717,
 3723,
 3724,
 3729,
 3731,
 3733,
 3749,
 3762,
 3763,
 3771,
 3772,
 3782,
 3790,
 3794,
 3795,
 3805,
 3818,
 3822,
 3827,
 3829,
 3842,
 3878,
 3895,
 3920,
 3938,
 3959,
 3995,
 4010,
 4012,
 4039,
 4118,
 4120,
 4121,
 4128,
 4134,
 4148,
 4149,
 4151,
 4155,
 4164,
 4166,
 4181,
 4200,
 4203,
 4208,
 4209,
 4210,
 4231,
 4235,
 4242,
 4245,
 4252,
 4256,
 4263,
 4303,
 4316,
 4317,
 4333,
 4343,
 4348,
 4354,
 4355,
 4361,
 4368,
 4376,
 4384,
 4386,
 4389,
 4396,
 4412,
 4415,
 4460,
 4462,
 4465,
 4476,
 4502,
 4518,
 4528,
 4532,
 4533,
 4534,
 4538,
 4561,
 4569,
 4576,
 4598,
 4624,
 4646,
 4668,
 4670,
 4672,
 4678,
 4681,
 4683,
 4832,
 4845,
 4956,
 4968,
 4982,
 4998,
 61511,
 61512,
 61513,
 61514,
 61515,
 61517,
 61518,
 61519,
 61520,
 61521,
 61523,
 61526,
 61528,
 61531,
 61532,
 61534,
 61535,
 61538,
 61540,
 61542,
 61544,
 61546,
 61548,
 61549,
 61552,
 61554,
 61558,
 61564,
 61566,
 61568,
 61569,
 61574,
 61576,
 61577,
 61578,
 61579,
 61580,
 61581,
 61584,
 61587,
 61588,
 61589,
 61591,
 61595,
 61600,
 61604,
 61606,
 61609,
 61610,
 107899,
 107902,
 107904,
 107906,
 107910,
 107911,
 107914,
 107917,
 107918,
 107919,
 107920,
 107921,
 107923,
 107924,
 107926,
 107927,
 107928,
 107929,
 107931,
 107936,
 107937,
 107938,
 107943,
 107945,
 107947,
 107949,
 107951,
 107953,
 107959,
 107971,
 107972,
 107973,
 107974,
 107980,
 107981,
 107983,
 107984,
 107986,
 107990,
 107991,
 107992,
 107994,
 107995,
 107997,
 150260,
 150261,
 150263,
 150264,
 150265,
 150267,
 150269,
 150270,
 150276,
 150277,
 150279,
 150280,
 150289,
 150291,
 150294,
 150295,
 150297,
 150301,
 150302,
 150303,
 150306,
 150307,
 150308,
 150309,
 150311,
 150312,
 150314,
 150315,
 150316,
 150317,
 150318,
 150322,
 150324,
 150325,
 150326,
 150327,
 150330,
 150331,
 150332,
 150335,
 150338,
 150341,
 150342,
 150343,
 150345,
 150348,
 150349,
 150351,
 150352,
 150353,
 150356,
 150357,
 150358,
 150359,
 150360,
 150361,
 150364,
 150368,
 150371,
 150372,
 150378,
 150380,
 150382,
 150383,
 150384,
 150385,
 150387,
 150389,
 150390,
 150392,
 150393,
 150395,
 150400,
 150408,
 150409,
 150410,
 150413,
 150414,
 150416,
 150420,
 150423,
 150425,
 150430,
 150431,
 150432,
 150433,
 150434,
 150435,
 150436,
 150439,
 150442,
 ...]

### Load images into database:

In [21]:

print("=" * 70)
print("STEP 1: LOADING VISUAL GENOME IMAGES")
print("=" * 70)

# Initialize MLDataLoader, this also establishes the connection with the database:
loader = MLDataLoader(db_name=database_name, source=file_source)

# Extract image information from TIF files
image_ids = []      # Will be integers: [2, 3, 8, 15, ...]
filenames = []      # Will be: ['BernerOberland002.tif', ...]
file_paths = []     # Full paths

for file in vg_files:  # tif_files from our earlier exploration
    # Extract numeric ID from filename
    name = file.stem  #
    match = re.search(r'(\d+)$', name)
    
    if match:
        id_int = int(match.group(1))  # '002' → 2 (integer)
        
        image_ids.append(id_int)
        filenames.append(file.name)
        file_paths.append(str(file))

# print(f"Found {len(image_ids)} images")
#print(f"Image IDs (integers): {sorted(image_ids)}")
# print()

# Load images using MLDataLoader
#id_mapping = loader.load_images(
result = loader.load_images_safe(
    image_ids=image_ids,
    filenames=filenames,
    file_paths=file_paths,
    source=file_source
)

print()

id_mapping = result['id_mapping']
new_files = result['inserted_files']
reused_files = result['existing_files']

print(f"✅ ID Mapping created: {len(id_mapping)} entries")
print("Sample mappings (source, source_image_id) → database_image_id:")
for key in sorted(id_mapping.keys())[:5]:
    print(f"  {key} → {id_mapping[key]}")
print('New files:')
print(len(new_files))
print(new_files[0:3])
print('Reused files:')
print(len(reused_files))
print(reused_files[0:3])

======================================================================
STEP 1: LOADING VISUAL GENOME IMAGES
======================================================================
✅ Connected to database: image_analysis_test
📊 Source dataset: visual_genome
📸 Loading 5354 images (source: visual_genome, safe mode)...
   ✅ 5354 new images loaded
   ✅ ID mapping created: 5354 entries

✅ ID Mapping created: 5354 entries
Sample mappings (source, source_image_id) → database_image_id:
  ('visual_genome', 1) → 667
  ('visual_genome', 2) → 668
  ('visual_genome', 9) → 669
  ('visual_genome', 11) → 670
  ('visual_genome', 16) → 671
New files:
5354
['visual_genome_proc_1.jpg', 'visual_genome_proc_2.jpg', 'visual_genome_proc_9.jpg']
Reused files:
0
[]

### Load ground truth into database:

In [22]:
import pandas as pd

print("=" * 70)
print("STEP 3: LOADING GROUND TRUTH (BUILDINGS LABEL)")
print("=" * 70)

label_data = label_data[['image_id', 'buildings']]

print(f"Loaded {len(label_data)} images with 'buildings' label")

# Transform label_data from wide to long format
label_data_long = label_data.melt(
    id_vars=['image_id'], 
    var_name='label_name',
    value_name='value'
)

# Convert image_id to integer (if it's a string)
label_data_long['image_id'] = label_data_long['image_id'].astype(int)

# Convert value from 0/1 to 'false'/'true'
label_data_long['value'] = label_data_long['value'].apply(lambda x: 'true' if x == 1 else 'false')

print(f"Transformed {len(label_data)} rows (wide) → {len(label_data_long)} rows (long)")
print(f"\nFirst few rows:")
print(label_data_long.head(10))
print()

# Load ground truth
result = loader.load_ground_truth_safe(label_data_long, source=file_source)

print("\n✅ Ground truth loading complete!")
print(f"   Inserted: {result['inserted']}")
print(f"   Existing: {result['existing']}")
print(f"   Skipped: {result['skipped']}")

======================================================================
STEP 3: LOADING GROUND TRUTH (BUILDINGS LABEL)
======================================================================
Loaded 5354 images with 'buildings' label
Transformed 5354 rows (wide) → 5354 rows (long)

First few rows:
   image_id label_name value
0         1  buildings  true
1         2  buildings  true
2         9  buildings  true
3        11  buildings  true
4        16  buildings  true
5        22  buildings  true
6        23  buildings  true
7        24  buildings  true
8        25  buildings  true
9        26  buildings  true

📋 Loading ground truth from DataFrame (safe mode)
   Found 5354 ground truth entries
   ✅ 5354 new ground truth entries loaded

✅ Ground truth loading complete!
   Inserted: 5354
   Existing: 0
   Skipped: 0

### Load analysis_runs data:

In [23]:
import pickle
file_path = visual_genome_path / metadata_results_file
# Load
with open(file_path, 'rb') as f:
    metadata_results_clustering = pickle.load(f)

In [24]:
metadata_results_clustering.keys()

dict_keys(['analysis_type', 'model_name', 'python_script', 'notes', 'autoencoder_name', 'autoencoder_implementation', 'run_timestamp', 'dim_reduction_name', 'dim_reduction_implementation', 'dim_reduction_params', 'clustering_name', 'clustering_implementation', 'clustering_params', 'autoencoder_params', 'cluster_data'])

In [25]:
metadata_results_clustering['autoencoder_params']

{'code_size': 120,
 'n_sample': 128,
 'noise rate': 0.1,
 'side length': 320,
 'n_train_images': 4282,
 'n_validation_images': 1072,
 'in_size': (320, 320),
 'number_epochs': 60,
 'learning_rate': 0.0009}

In [26]:
metadata_results_clustering['cluster_data'].head()

,image_index,cluster_label,class_label,image_paths,feature_1,feature_2,image_id
0,0,5,0,/Users/stephanehess/Documents/CAS_AML/dias_dig...,-8.481663,-27.291840,2355846
1,1,3,0,/Users/stephanehess/Documents/CAS_AML/dias_dig...,-43.099529,17.845493,498178
2,2,7,0,/Users/stephanehess/Documents/CAS_AML/dias_dig...,50.374680,7.010959,2339429
3,3,2,0,/Users/stephanehess/Documents/CAS_AML/dias_dig...,25.367308,-39.825848,2361902
4,4,6,0,/Users/stephanehess/Documents/CAS_AML/dias_dig...,-57.249519,65.263962,2345026

### Load times data:

In [27]:
import pickle
file_path = visual_genome_path / times_file
# Load
with open(file_path, 'rb') as f:
    times_data = pickle.load(f)

In [28]:
times_data

{'analysis_name': ['clustering_pipeline'],
 'time_stamp_start': [Timestamp('2026-02-08 22:52:15.995956')],
 'duration_str': ['Analysis took: 0 days 00:59:02.313392'],
 'duration_seconds': [3542.313392],
 'duration_seconds_str': ['Analysis took: 3542.31 seconds'],
 'duration_minutes': [59.038556533333335],
 'duration_minutes_str': ['Analysis took: 59.04 minutes']}

### Get numbers of train, validation, and total images processed:

In [29]:
# Get numbers of train, validation, and total images processed:
n_train_images = metadata_results_clustering['autoencoder_params']['n_train_images']
print(n_train_images)

n_validation_images = metadata_results_clustering['autoencoder_params']['n_validation_images']
print(n_validation_images)
n_images = n_train_images + n_validation_images
n_images

4282
1072

5354

In [30]:
metadata_results_clustering['run_timestamp']
metadata_results_clustering['analysis_type']
metadata_results_clustering['model_name']
metadata_results_clustering['python_script']
times_data['duration_seconds']
metadata_results_clustering['autoencoder_name']
metadata_results_clustering['autoencoder_implementation']
metadata_results_clustering['autoencoder_params']
metadata_results_clustering['dim_reduction_name'][0]
metadata_results_clustering['dim_reduction_implementation']
metadata_results_clustering['dim_reduction_params']
metadata_results_clustering['clustering_name']
metadata_results_clustering['clustering_params']
metadata_results_clustering['clustering_implementation']

'sklearn.cluster.KMeans'

In [31]:
metadata_results_clustering['run_timestamp']
metadata_results_clustering['analysis_type']

'clustering'

### Load analysis runs data into database:

In [32]:
analysis_run_id = loader.load_analysis_run(run_timestamp = metadata_results_clustering['run_timestamp'], 
                         analysis_type = metadata_results_clustering['analysis_type'], 
                         model_name = metadata_results_clustering['model_name'], 
                         python_script = metadata_results_clustering['python_script'], 
                         model_version=None, 
                         hyperparameters=None, 
                         notes='Analysed amples taken from training set (cheating).', 
                         start_time=None, 
                         duration_seconds = times_data['duration_seconds'][0], 
                         images_processed = n_images, 
                         # Clustering pipeline parameters (all optional) 
                         autoencoder_name = 'convolutional_autoencoder', 
                         autoencoder_implementation = metadata_results_clustering['autoencoder_implementation'], 
                         autoencoder_file = model_file_path, 
                         autoencoder_params = metadata_results_clustering['autoencoder_params'], 
                         dim_reduction_name = metadata_results_clustering['dim_reduction_name'][0], 
                         dim_reduction_implementation = metadata_results_clustering['dim_reduction_implementation'], 
                         dim_reduction_params = metadata_results_clustering['dim_reduction_params'], 
                         clustering_name = metadata_results_clustering['clustering_name'], 
                         clustering_implementation = metadata_results_clustering['clustering_implementation'], 
                         clustering_params = metadata_results_clustering['clustering_params'])
analysis_run_id

6

In [33]:
#loader.conn.rollback()

### Load results into database:

In [34]:
result = loader.load_clustering_results(
    analysis_run_id=analysis_run_id,
    clustering_dataframe=metadata_results_clustering['cluster_data'],
    source=file_source
)

📊 Loading clustering results (source: visual_genome)...
   Found 256 cluster assignments
   ✅ 256 clustering results loaded

In [35]:
# Close cursor and connection
loader.cur.close()
loader.conn.close()

In [36]:
# ============================================================================
# CLUSTERING DATA VERIFICATION
# ============================================================================
import pandas as pd
import psycopg2
from dotenv import load_dotenv
import os

load_dotenv()

conn = psycopg2.connect(
    dbname=os.getenv('DB_NAME'),
    user=os.getenv('DB_USER'),
    password=os.getenv('DB_PASSWORD'),
    host=os.getenv('DB_HOST'),
    port=os.getenv('DB_PORT')
)

print("=" * 80)
print("CLUSTERING DATA VERIFICATION")
print("=" * 80)

# ---------------------------------------------------------------------------
# 1. Check Visual Genome Images Loaded
# ---------------------------------------------------------------------------
print("\n1. VISUAL GENOME IMAGES")
print("-" * 80)

query1 = """
SELECT 
    source,
    COUNT(*) as image_count,
    MIN(source_image_id) as min_id,
    MAX(source_image_id) as max_id
FROM images
WHERE source = 'visual_genome'
GROUP BY source;
"""

df1 = pd.read_sql_query(query1, conn)
print(df1.to_string(index=False))

if len(df1) == 0:
    print("\n⚠️  WARNING: No visual_genome images found!")
else:
    print(f"\n✅ Found {df1['image_count'].iloc[0]} Visual Genome images")

================================================================================
CLUSTERING DATA VERIFICATION
================================================================================

1. VISUAL GENOME IMAGES
--------------------------------------------------------------------------------
       source  image_count  min_id  max_id
visual_genome         5354       1 2417729

✅ Found 5354 Visual Genome images

/var/folders/p2/j3lbpcl141q66c1kqyxwsc3w0000gn/T/ipykernel_26580/4021728845.py:40: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df1 = pd.read_sql_query(query1, conn)

In [37]:
# ---------------------------------------------------------------------------
# 2. Check Clustering Analysis Run
# ---------------------------------------------------------------------------
print("\n\n2. CLUSTERING ANALYSIS RUN DETAILS")
print("-" * 80)

query2 = """
SELECT 
    analysis_run_id,
    run_timestamp,
    model_name,
    analysis_type,
    autoencoder_name,
    autoencoder_implementation,
    dim_reduction_name,
    dim_reduction_implementation,
    clustering_name,
    clustering_implementation
FROM analysis_runs
WHERE analysis_type = 'clustering'
ORDER BY run_timestamp DESC
LIMIT 1;
"""

df2 = pd.read_sql_query(query2, conn)
if len(df2) == 0:
    print("⚠️  WARNING: No clustering analysis run found!")
    clustering_run_id = None
else:
    print(df2.transpose().to_string())
    clustering_run_id = df2['analysis_run_id'].iloc[0]
    print(f"\n✅ Found clustering analysis run (ID: {clustering_run_id})")

2. CLUSTERING ANALYSIS RUN DETAILS
--------------------------------------------------------------------------------
                                                                    0
analysis_run_id                                                     6
run_timestamp                              2026-02-08 22:52:15.995956
model_name                                        clustering pipeline
analysis_type                                              clustering
autoencoder_name                            convolutional_autoencoder
autoencoder_implementation    Custom PyTorch ConvolutionalAutoEncoder
dim_reduction_name                                               TSNE
dim_reduction_implementation                    sklearn.manifold.TSNE
clustering_name                                               K-Means
clustering_implementation                      sklearn.cluster.KMeans

✅ Found clustering analysis run (ID: 6)

/var/folders/p2/j3lbpcl141q66c1kqyxwsc3w0000gn/T/ipykernel_26580/2992599622.py:25: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df2 = pd.read_sql_query(query2, conn)

In [38]:
# ---------------------------------------------------------------------------
# 3. Check Clustering Results Loaded
# ---------------------------------------------------------------------------
print("\n\n3. CLUSTERING RESULTS")
print("-" * 80)

if clustering_run_id:
    query3 = f"""
    SELECT 
        COUNT(*) as total_assignments,
        COUNT(DISTINCT cluster_id) as num_clusters,
        COUNT(DISTINCT image_id) as images_clustered,
        MIN(cluster_id) as min_cluster,
        MAX(cluster_id) as max_cluster
    FROM clustering_results
    WHERE analysis_run_id = {clustering_run_id};
    """
    
    df3 = pd.read_sql_query(query3, conn)
    print(df3.to_string(index=False))
    
    if df3['total_assignments'].iloc[0] == 0:
        print("\n⚠️  WARNING: No clustering results found!")
    else:
        print(f"\n✅ {df3['total_assignments'].iloc[0]} cluster assignments loaded")
        print(f"   Clusters: {df3['num_clusters'].iloc[0]} unique clusters")
        print(f"   Images: {df3['images_clustered'].iloc[0]} images clustered")
else:
    print("⚠️  Skipping - no clustering run found")

3. CLUSTERING RESULTS
--------------------------------------------------------------------------------
 total_assignments  num_clusters  images_clustered  min_cluster  max_cluster
               256            12               256            0           11

✅ 256 cluster assignments loaded
   Clusters: 12 unique clusters
   Images: 256 images clustered

/var/folders/p2/j3lbpcl141q66c1kqyxwsc3w0000gn/T/ipykernel_26580/1870217417.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df3 = pd.read_sql_query(query3, conn)

In [39]:
# ---------------------------------------------------------------------------
# 4. Check Ground Truth (Buildings Label)
# ---------------------------------------------------------------------------
print("\n\n4. GROUND TRUTH - BUILDINGS LABEL")
print("-" * 80)

query4 = """
SELECT 
    COUNT(*) as total_labels,
    SUM(CASE WHEN value = 'true' THEN 1 ELSE 0 END) as with_buildings,
    SUM(CASE WHEN value = 'false' THEN 1 ELSE 0 END) as without_buildings
FROM ground_truth_history gt
JOIN images i ON gt.image_id = i.image_id
WHERE i.source = 'visual_genome'
  AND gt.label_name = 'buildings'
  AND gt.is_current = TRUE;
"""

df4 = pd.read_sql_query(query4, conn)
print(df4.to_string(index=False))

if df4['total_labels'].iloc[0] == 0:
    print("\n⚠️  WARNING: No 'buildings' ground truth found!")
else:
    print(f"\n✅ {df4['total_labels'].iloc[0]} images labeled for buildings")

4. GROUND TRUTH - BUILDINGS LABEL
--------------------------------------------------------------------------------
 total_labels  with_buildings  without_buildings
         5354            2677               2677

✅ 5354 images labeled for buildings

/var/folders/p2/j3lbpcl141q66c1kqyxwsc3w0000gn/T/ipykernel_26580/398766505.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df4 = pd.read_sql_query(query4, conn)

In [40]:

# ---------------------------------------------------------------------------
# 5. Cluster Distribution
# ---------------------------------------------------------------------------
print("\n\n5. CLUSTER DISTRIBUTION")
print("-" * 80)

if clustering_run_id:
    query5 = f"""
    SELECT 
        cr.cluster_id,
        COUNT(*) as image_count,
        ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) as percentage
    FROM clustering_results cr
    WHERE cr.analysis_run_id = {clustering_run_id}
    GROUP BY cr.cluster_id
    ORDER BY cr.cluster_id;
    """
    
    df5 = pd.read_sql_query(query5, conn)
    print(df5.to_string(index=False))
    print(f"\n✅ Cluster distribution shown above")
else:
    print("⚠️  Skipping - no clustering run found")

5. CLUSTER DISTRIBUTION
--------------------------------------------------------------------------------
 cluster_id  image_count  percentage
          0           47       18.36
          1           29       11.33
          2           35       13.67
          3           24        9.38
          4           17        6.64
          5           35       13.67
          6            2        0.78
          7           10        3.91
          8            3        1.17
          9           21        8.20
         10           13        5.08
         11           20        7.81

✅ Cluster distribution shown above

/var/folders/p2/j3lbpcl141q66c1kqyxwsc3w0000gn/T/ipykernel_26580/2236874828.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df5 = pd.read_sql_query(query5, conn)

In [41]:

# ---------------------------------------------------------------------------
# 6. Buildings Label by Cluster (Combined View)
# ---------------------------------------------------------------------------
print("\n\n6. BUILDINGS LABEL DISTRIBUTION BY CLUSTER")
print("-" * 80)

if clustering_run_id:
    query6 = f"""
    SELECT 
        cr.cluster_id,
        COUNT(*) as total_images,
        SUM(CASE WHEN gt.value = 'true' THEN 1 ELSE 0 END) as with_buildings,
        SUM(CASE WHEN gt.value = 'false' THEN 1 ELSE 0 END) as without_buildings,
        ROUND(
            100.0 * SUM(CASE WHEN gt.value = 'true' THEN 1 ELSE 0 END) / COUNT(*),
            2
        ) as buildings_percentage
    FROM clustering_results cr
    JOIN images i ON cr.image_id = i.image_id
    LEFT JOIN ground_truth_history gt 
        ON cr.image_id = gt.image_id 
        AND gt.label_name = 'buildings'
        AND gt.is_current = TRUE
    WHERE cr.analysis_run_id = {clustering_run_id}
    GROUP BY cr.cluster_id
    ORDER BY cr.cluster_id;
    """
    
    df6 = pd.read_sql_query(query6, conn)
    print(df6.to_string(index=False))
    print(f"\n✅ Buildings distribution by cluster shown above")
else:
    print("⚠️  Skipping - no clustering run found")

6. BUILDINGS LABEL DISTRIBUTION BY CLUSTER
--------------------------------------------------------------------------------
 cluster_id  total_images  with_buildings  without_buildings  buildings_percentage
          0            47              19                 28                 40.43
          1            29              17                 12                 58.62
          2            35              19                 16                 54.29
          3            24              13                 11                 54.17
          4            17               5                 12                 29.41
          5            35              20                 15                 57.14
          6             2               0                  2                  0.00
          7            10               6                  4                 60.00
          8             3               2                  1                 66.67
          9            21              10                 11                 47.62
         10            13               9                  4                 69.23
         11            20               8                 12                 40.00

✅ Buildings distribution by cluster shown above

/var/folders/p2/j3lbpcl141q66c1kqyxwsc3w0000gn/T/ipykernel_26580/3642692300.py:29: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df6 = pd.read_sql_query(query6, conn)

In [42]:



# ---------------------------------------------------------------------------
# 7. Sample of Clustering Results with Details
# ---------------------------------------------------------------------------
print("\n\n7. SAMPLE CLUSTERING RESULTS (First 10 images)")
print("-" * 80)

if clustering_run_id:
    query7 = f"""
    SELECT 
        i.filename,
        i.source_image_id,
        cr.cluster_id,
        gt.value as has_buildings
    FROM clustering_results cr
    JOIN images i ON cr.image_id = i.image_id
    LEFT JOIN ground_truth_history gt 
        ON cr.image_id = gt.image_id 
        AND gt.label_name = 'buildings'
        AND gt.is_current = TRUE
    WHERE cr.analysis_run_id = {clustering_run_id}
    ORDER BY i.source_image_id
    LIMIT 10;
    """
    
    df7 = pd.read_sql_query(query7, conn)
    print(df7.to_string(index=False))
else:
    print("⚠️  Skipping - no clustering run found")

# Close connection
conn.close()

print("\n" + "=" * 80)
print("VERIFICATION COMPLETE")
print("=" * 80)

7. SAMPLE CLUSTERING RESULTS (First 10 images)
--------------------------------------------------------------------------------
                  filename  source_image_id  cluster_id has_buildings
 visual_genome_proc_56.jpg               56           1          true
visual_genome_proc_137.jpg              137           3          true
visual_genome_proc_208.jpg              208          10          true
visual_genome_proc_290.jpg              290           8         false
visual_genome_proc_303.jpg              303           0          true
visual_genome_proc_319.jpg              319           2          true
visual_genome_proc_436.jpg              436           3          true
visual_genome_proc_443.jpg              443           9          true
visual_genome_proc_456.jpg              456          10          true
visual_genome_proc_488.jpg              488           2          true

================================================================================
VERIFICATION COMPLETE
================================================================================

/var/folders/p2/j3lbpcl141q66c1kqyxwsc3w0000gn/T/ipykernel_26580/42003804.py:25: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df7 = pd.read_sql_query(query7, conn)