In [14]:
import os
from pathlib import Path
from PIL import Image
import shutil
import pandas as pd
from source import image_id_converter as img_idc

In [3]:
import csv

In [4]:
os.getcwd()

'/Users/stephanehess/Documents/CAS_AML/dias_digit_project/project'

In [5]:
#import functions as fn

In [6]:
os.getcwd()

'/Users/stephanehess/Documents/CAS_AML/dias_digit_project/project'

In [7]:
root_path = Path('/Users/stephanehess/Documents/CAS_AML/dias_digit_project/project')

In [8]:
os.chdir(root_path)

In [8]:

# Define paths
image_dir = root_path/"../data"  # Replace with your directory containing images
#output_dir_with_person = root_path/"../with_person"  # Replace with output directory for images with persons
#output_dir_without_person = root_path/"../without_person"  # Replace with output directory for images without persons

In [9]:
with_without_person_raw = pd.read_csv(image_dir/'with_without_person.csv')
with_without_person_raw['recognisable'] = with_without_person_raw['recognisable'].fillna(0).astype(int)
with_without_person = with_without_person_raw.iloc[:,0:3]
with_without_person

     image_id  with_person  recognisable
0         111            1             0
1           1            1             1
2           2            0             0
3           3            0             0
4           4            0             0
..        ...          ...           ...
106       106            0             0
107       107            0             0
108       108            1             0
109       109            0             0
110       110            0             0

[111 rows x 3 columns]

In [10]:
# Convert labels to strings:
img_ids = list(with_without_person.image_id)
img_ids_strings = [str(x) for x in img_ids]
img_ids_strings[:3]

['111', '1', '2']

In [12]:
with_without_person['image_id'] = img_idc.complete_image_ids(img_ids_strings)

In [13]:
type(with_without_person['image_id'][0])

str

In [14]:
with_without_person.head()

  image_id  with_person  recognisable
0    id111            1             0
1    id001            1             1
2    id002            0             0
3    id003            0             0
4    id004            0             0

In [15]:
with_without_person

    image_id  with_person  recognisable
0      id111            1             0
1      id001            1             1
2      id002            0             0
3      id003            0             0
4      id004            0             0
..       ...          ...           ...
106    id106            0             0
107    id107            0             0
108    id108            1             0
109    id109            0             0
110    id110            0             0

[111 rows x 3 columns]

In [16]:
with_without_person.sort_values(by='image_id', inplace=True)

In [17]:
with_without_person

    image_id  with_person  recognisable
1      id001            1             1
2      id002            0             0
3      id003            0             0
4      id004            0             0
5      id005            0             0
..       ...          ...           ...
107    id107            0             0
108    id108            1             0
109    id109            0             0
110    id110            0             0
0      id111            1             0

[111 rows x 3 columns]

In [18]:
with_without_person.reset_index(inplace=True, drop=True)

In [19]:
with_without_person

    image_id  with_person  recognisable
0      id001            1             1
1      id002            0             0
2      id003            0             0
3      id004            0             0
4      id005            0             0
..       ...          ...           ...
106    id107            0             0
107    id108            1             0
108    id109            0             0
109    id110            0             0
110    id111            1             0

[111 rows x 3 columns]

In [20]:
os.getcwd()

'/Users/stephanehess/Documents/CAS_AML/dias_digit_project/project'

In [21]:
with_without_person.to_csv(image_dir/'with_without_person_mod.csv', index=False)

In [22]:
with_without_person = pd.read_csv(image_dir/'with_without_person_mod.csv')
with_without_person

    image_id  with_person  recognisable
0      id001            1             1
1      id002            0             0
2      id003            0             0
3      id004            0             0
4      id005            0             0
..       ...          ...           ...
106    id107            0             0
107    id108            1             0
108    id109            0             0
109    id110            0             0
110    id111            1             0

[111 rows x 3 columns]

def reconvert_image_ids(image_ids):
    new_image_ids = []
    for image_id in image_ids:
        new_image_id = image_id.split('id')[1]
        new_image_ids.append(new_image_id)
    return new_image_ids

In [23]:
img_ids = list(with_without_person.image_id)

In [24]:
with_without_person.image_id = img_idc.reconvert_image_ids(img_ids)

In [25]:
with_without_person

    image_id  with_person  recognisable
0        001            1             1
1        002            0             0
2        003            0             0
3        004            0             0
4        005            0             0
..       ...          ...           ...
106      107            0             0
107      108            1             0
108      109            0             0
109      110            0             0
110      111            1             0

[111 rows x 3 columns]